training:
  vector_size: 300
  hidden_size: 400
  output_size: 100
  gamma: 0.9
  learning_rate: 1e-5
  batch_size: 8
  max_nb_steps_per_episode: 50
  entropy_coefficient: 0.01
  device: cpu
testing:
  test_time: True
  use_pretrained_model: True
